# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b297cbc7f5d4e3651ec495e3212623966dc7f2114b6a358f0eb847a3ae35ff52e585c36ded85138d8a14b8dd71b01b94f263e8b925258b81414028d80fb68f82

test:
  secret_key_base: 885b3e21424f7731429d65e88f2153f9f709cca175ddc181c6fcaaf6e424cab02ee7c7a49d7645dd5b674ca8520656549c31ec5a075ae8d0cc58fd3e5f84b7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
